version: '3.3'

services:
    ycast-docker:
        container_name: ycast
        build: ./YCast/docker
        environment:
            - YC_STATIONS=/opt/ycast/stations/stations.yml
            - YC_DEBUG=ON
            - TZ=Europe/Amsterdam
            - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
            - YC_VERSION=master
            - YC_PORT=80
        volumes:
            - /home/ubuntu/docker/ycast/stations:/opt/ycast/stations
        restart: always
        ports:
           - "80:80"
